// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6kaCLnApNqjbaTvFC514CsPC1NMxrKbQ',
    appId: '1:268491461507:web:83d56e46de13ad9c135cb6',
    messagingSenderId: '268491461507',
    projectId: 'deprem-konut-hasar2',
    authDomain: 'deprem-konut-hasar2.firebaseapp.com',
    storageBucket: 'deprem-konut-hasar2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC584GF2pvJ7JucCdnoITDNKzF-MMfXePU',
    appId: '1:268491461507:android:4d47956409cf1903135cb6',
    messagingSenderId: '268491461507',
    projectId: 'deprem-konut-hasar2',
    storageBucket: 'deprem-konut-hasar2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCToUWN_Ec_haDc0mp2hPvolVB9TwEJ81A',
    appId: '1:268491461507:ios:328b6733d441e3ce135cb6',
    messagingSenderId: '268491461507',
    projectId: 'deprem-konut-hasar2',
    storageBucket: 'deprem-konut-hasar2.appspot.com',
    iosBundleId: 'com.example.hasarKonut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCToUWN_Ec_haDc0mp2hPvolVB9TwEJ81A',
    appId: '1:268491461507:ios:c7cbf8f0cf60bcf0135cb6',
    messagingSenderId: '268491461507',
    projectId: 'deprem-konut-hasar2',
    storageBucket: 'deprem-konut-hasar2.appspot.com',
    iosBundleId: 'com.example.hasarKonut.RunnerTests',
  );
}
